### ISSUE TITLE
Bluetooth audio (headset) stuttering when using both wifi and bluetooth

### ISSUE THREAD

**Issue by abraaocaldas** [CyanogenMod/android_device_samsung_klteduos#1]
Hello, if you use the Android Wifi Tethering and Bluetooth audio at same time, it renders the bluetooth radio unusable.

Device: SM-G900MD
Band Base: G900MDUBU1BOB2
Cyanogen Version: 12.1-20150816-NIGHTLY-klteduos
Audio HeadSet: Philips SHB4000

Steps to reproduce:

Connect the bluetooth headset / Play Music (can be via Google Music, Spotify... etc)
Start an access point (wifi tethering)
Connect another device via wifi
Start data transfer
Monitor audio
Alternative Way:
1 ~ 2. Same as default way
3. Go to settings
4. Tap on bluetooth -> Search for devices
5. Monitor audio

Actual result
5. Audio Stuttering

Expected result
5. The playing music should be correct.

**Comment by meiser79** [comment]
Did you try adding "ro.bluetooth.request.master=true" in the /system/build.prop file?
